### ISSUE TITLE
Comments.cs only loads first 25?

### ISSUE THREAD

**Issue by earthlion** [sirkris/Reddit.NET#108]
Hi there

It seems like the Comments.cs only returns 25 on either interface.
How does one interate through the full comment tree of a post or comment?

**Comment by sirkris** [comment]
You can get around this by calling the Get* methods and passing the limit parameter.  For example, instead of....

comment.Comments.New

Use:

comment.Comments.GetNew(limit: 100)

If you're trying to actually paginate beyond that, it can get a bit tricky and the API has historically behaved inconsistently in this regard.  According to the API docs, there's no option to supply the usual "after" paramteter that you can for paginating posts and other things.  However, according to anecdotal sources like this:

https://www.reddit.com/r/redditdev/comments/jwkfds/pagination_in_comments_api/

....passing the after parameter should work just fine.  But then, if you click the example link in that old post, it doesn't work.  Ugh.

That's why the library doesn't support it.  If you can put together a test and show me a reliable method of getting the API to accept the before/after params for the /comments endpoint, I'll gladly add it to the library.  But it looks like this is an issue you'd probably want to take up with Reddit's admins.

**Comment by bugproof** [comment]
What about the pagination of subreddit posts? Is it possible or is "before" and "after" not supported here as well? It only returns 101 posts.
