### ISSUE TITLE
AddRelationship does not allow permanent bans

### ISSUE THREAD

**Issue by kyleratti** [sirkris/Reddit.NET#119]
Unless I am missing something, the `AddRelationship(...)` function does not allow issuing a permanent ban as it requires a duration of type `int`.

https://github.com/sirkris/Reddit.NET/blob/ae1267b6e9f2360f41d1703af51cc64e27c07617/src/Reddit.NET/Controllers/User.cs#L625

Is there another way we are supposed to issue a permanent ban via the library or is this a bug?

**Comment by sirkris** [comment]
I think this one would qualify as a library bug.  The API documentation
doesn't say anything about permanent bans, but I was able to find this:

https://www.reddit.com/r/redditdev/comments/gditbx/praw_permanent_bans_with_duration/

I'm guessing that's what you want to do but can't because the library
forces you to pass something for duration?  If so, then yeah that's a bug
that'll need to be fixed.  Would've been nice if the API docs mentioned
that this field is optional and that omitting it is required to make a
relationship permanent....

**Comment by kyleratti** [comment]
Hi Kris,

Yes, you're correct, it's requiring an int and unfortunately the API won't take 0 or -1 as permanent.

I agree - it's not listed anywhere I could find, either. Frustrating.

Is this something that you plan to fix or would you like a PR for it?
________________________________

**Comment by sirkris** [comment]
Either way is fine.  I'm hoping to find time to start working on the next
release soon but certainly any PRs that reduce the number of outstanding
issues would be most helpful.

**Comment by kyleratti** [comment]
I'll see if I get some time to do it.

Do you have a preferred method for approaching this? A dedicated AddBan function that takes a nullable duration?

**Comment by kyleratti** [comment]
Quick update: setting duration to be nullable is all that's necessary. I'm not sure if it's sending a null value to the reddit API or omitting it entirely, but it gets processed correctly.

I'll send a PR through this evening!

**Comment by sirkris** [comment]
Yeah you got it right.  All that needs to be done is to make the argument
nullable.  Note that this needs to be done in both the controllers and
models, including the asyncs.

--Kris

**Comment by sirkris** [comment]
Merged into 1.5.

**Comment by kyleratti** [comment]
Thanks @sirkris. Apologies I didn't have time to get a PR to you for this.

**Comment by sirkris** [comment]
No worries, you still helped.  =)

**Comment by kyleratti** [comment]
Just wanted to confirm that when linked against `1.4.0-develop`, permanent bans work as intended!

Thanks again :)
