### ISSUE TITLE
No way to update client prefs

### ISSUE THREAD

**Issue by Thalitech** [sirkris/Reddit.NET#120]
I am writing a discord bot that ties into reddit and pulls post  but as the bot will be able to be added by any user. I want my bot to be able to access NSFW content as well but I am unable to update the over 18 parameter

my code 
```CS
  public RedditManager(CommandContext ctx = default)
        {
            var appID = new ResourceFile<string>()["reddit_appid", encrypt: true];
            var appSecret = new ResourceFile<string>()["reddit_secret", encrypt: true];
            reddit = new RedditClient(appID, appSecret: appSecret, userAgent: "Nami");
            reddit.Account.Me.Over18 = true;
            reddit.Account.UpdatePrefsAsync(new AccountPrefsSubmit(reddit.Account.Prefs(), null, false, null)).GetAwaiter().GetResult();
            Console.WriteLine($"Reddit Nami is {(reddit.Account.Me.Over18 ? "18+" : "Under age")}");
            if(ctx != null)
            {
                this.context = ctx;
            }
        }
```
just need a little more help or at least a discord community I can post in or something

**Comment by sirkris** [comment]
The problem is that you're not passing the changes you've made to the Over18 property to the API.  This is because Account.UpdatePrefsAsync only uses whatever you input to the method for the update; it doesn't actually use the properties of the Account instance for this.

You want to change these two lines:

`reddit.Account.Me.Over18 = true;
reddit.Account.UpdatePrefsAsync(new AccountPrefsSubmit(reddit.Account.Prefs(), null, false, null)).GetAwaiter().GetResult();`

To this:

`AccountPrefs prefs = reddit.Account.Prefs();
prefs.Over18 = true;
reddit.Account.UpdatePrefsAsync(new AccountPrefsSubmit(prefs, null, false, null)).GetAwaiter().GetResult();`

That should work.  Basically, you need to query Account.Prefs() as you're doing, but then you need to modify that Over18 property of that return, and then send that modified instance back to Account.UpdatePrefs().

Please feel free to reopen this issue if you're still having trouble.
