### ISSUE TITLE
accessToken Not refreshing after expiration (1 hour)

### ISSUE THREAD

**Issue by drbergeron** [sirkris/Reddit.NET#128]
using a script style secret and providing an access token to the RedditClient constructor, after an hour the monitoring stops working and i'm assuming this is due to the access token expiring (most likely cause). 

The code looks good but reddit may be returning a weird response code or something that's not being caught in  GetResponse.

I can't see enough into the internals or logging to see what it's returning from the calls to reddit, but it's not throwing any errors to the calling program.

so wanted to report this, maybe as an easy work around make the token refresh method public so we can schedule it ourselves if we wanted to from the calling program?

code:
`var token = GetAccessToken(); //method that gets my access token from reddit endpoint
reddit = new RedditClient(appId: "appidhere", appSecret: "secrethere", accessToken: token, userAgent: "agent string");
                    //get subreddit
                    var wsbogs = reddit.Subreddit("subreddit name").About();
                    var firstpost = wsbogs.Posts.Hot.First();
                    var postToMonitor = firstpost.Listing.Stickied ? firstpost : null;

                    postToMonitor.Comments.GetNew();  // This call prevents any existing "new"-sorted comments from triggering 
                    postToMonitor.Comments.MonitorNew();
                    postToMonitor.Comments.NewUpdated += C_NewCommentsUpdated;
                    //after 1 hour the reddit event delegate stops monitoring and it not auto refreshing:`
                    
                    from debug where i'm logging from the event delegate:
                    first comment: Worker: Information: 2/20/2021 10:20:41 PM
                    last comment: Worker: Information: 2/20/2021 11:18:14 PM

**Comment by sirkris** [comment]
I'm curious as to the contents of your GetAccessToken() method, since that's where the token refresh would occur.  Are you trying to use app-only authentication?  If not, then you need to provide a refresh token in order to keep the access token from expiring.

If you already have a refresh token, you can get rid of GetAccesssToken() completely and just pass the refresh token to RedditClient.  The library will then automatically obtain a new access token as needed, but only if you pass the refresh token to the instance.

**Comment by drbergeron** [comment]
this is a script style one login vs. one where a user would provide their own login creds, here's the code for GetAccessToken();

`  private string GetAccessToken()
        {
            redditClient.Authenticator = new HttpBasicAuthenticator($"{config.Value.Reddit_appId}", $"{config.Value.Reddit_appSecret}");
            var request = new RestRequest("api/v1/access_token", Method.POST);
            request.AddHeader("Content-Type", "application/x-www-form-urlencoded");
            request.AddParameter("application/x-www-form-urlencoded", $"grant_type=password&username={config.Value.Reddit_login_urlencoded}&password={config.Value.Reddit_pass_urlencoded}", ParameterType.RequestBody);
            var response = redditClient.Execute<OauthResponse>(request);
            return response.Data.access_token;
        }`
        
        redditClient is a RestSharp RestClient class

**Comment by Dayjay** [comment]
I have the same issue and would appreciate a solution.

**Comment by sirkris** [comment]
Sorry I missed your reply.  The problem here is that Reddit.NET doesn't support username/password authenticaiton for security reasons.  That said, this can be very easily fixed by using the AuthTokenRetrieverLib to obtain the necessary tokens.  Instead of collecting a user's username/password, they'd be redirected to a special authorization page on Reddit.  If they're not logged-in, Reddit will prompt them for username/password.

Once the user clicks "accept", the tokens are posted to your app's callback URL.  You can then use that refresh token from then on instead of having to store their username/password somewhere.  This is a one-time step that a new user would have to go through; after that, the stored refresh token should be good indefinitely so long as it doesn't get revoked for whatever reason.

I would STRONGLY encourage both of you to switch to this OAuth workflow.  You can then just get rid of GetAccessToken() entirely, as Reddit.NET automatically does all this for you.

**Comment by Dayjay** [comment]
Thanks you, seems to work fine for me.

**Comment by sirkris** [comment]
Issue was resolved so closing.  Please feel free to reopen if you're still having issues.
