### ISSUE TITLE
Monitoring /r/all for new comments/posts

### ISSUE THREAD

**Issue by kyleratti** [sirkris/Reddit.NET#132]
Hi,

Is there something different I need to do to be able to monitor /r/all? My event handler never seems to fire, and `_all.Comments.GetNew()` just throws for unparsable JSON (which I think may be normal for "special" subreddits like `all` and `popular`?)

```cs
var _redditClient = new Lazy<RedditClient>(() => new RedditClient("appId", "appSecret", "refreshToken", "userAgent");
var all = _redditClient.Value.Subreddit("all");
_all.Comments.NewUpdated += (object? sender, CommentsUpdateEventArgs e) =>
{
	_logger.LogInformation("A new comment was posted");
};

_all.Comments.MonitorNew();
```

My logger never seems to fire. Same result when adding a new submission scanner right below it:

```cs
_all.Posts.NewUpdated += (object? sender, PostsUpdateEventArgs e) =>
{
	_logger.LogInformation("A new submission was posted");
};
_all.Posts.MonitorNew();
```

End goal is to monitor all new submissions/comments across all of reddit.

Thanks

**Comment by sirkris** [comment]
Monitoring r/all should be no different.  Have you tried declaring an actual callback method instead of doing it inline?  Can't say for sure without seeing the rest of the code but your callback might not be persisting as a result.

For example, this:

`_all.Posts.NewUpdated += (object? sender, PostsUpdateEventArgs e) =>
{
	_logger.LogInformation("A new submission was posted");
};`

Becomes this:

`private void C_PostsUpdated(object sender, PostsUpdateEventArgs e)
{
   _logger.LogInformation("A new submission was posted");
}
_all.Posts.NewUpdated += C_PostsUpdated;
`

Try that and let me know if it works.

**Comment by kyleratti** [comment]
Kris,

Thanks for the swift response! As requested, an equivalent with lambdas:

```cs
{
	_all.Posts.NewUpdated += PostsOnNewUpdated;
}

// ...

private void PostsOnNewUpdated(object? sender, PostsUpdateEventArgs e)
{
	_logger.LogInformation("A new submission was posted");
}
```

Never fires.

**Comment by kyleratti** [comment]
You have my most sincere apologies; I messed up my dependency injection and all of my credentials were null.
