### ISSUE TITLE
JsonSerializationException

### ISSUE THREAD

**Issue by IsaaacD** [sirkris/Reddit.NET#149]
When I try to access RedditClient.Account.Me I get the following issue 
![image](https://user-images.githubusercontent.com/5303125/173719498-f3562dc2-d8d2-4231-8d8f-c1f76812b6c3.png)
Is this something that has changed? I was using the Nuget package and it stopped working today, I've been playing with it for a few weeks without issue.

Please advise

The error reads:
'Error converting value {null} to type 'System.Boolean'. Path 'subreddit.user_is_muted', line 1, position 477.'

**Comment by IsaaacD** [comment]
If I change UserSubreddit.cs line 32 to have a nullable boolean it works
` public bool? UserIsMuted { get; set; }`

**Comment by IsaaacD** [comment]
It might be worth considering making all the types nullable incase something like this pops up for other properties

**Comment by sirkris** [comment]
@IsaaacD Yeah I've gone back and forth on this one.  I really want the properties to map to their API counterparts as closely as possible (especially in the Models/Things layer).  So if a user sees a property that's nullable, they'll know at a glance that the API can return null for that field.

The main problem I see with making everything nullable is that it makes the userland code needlessly clunky.  I mean, to have hundreds of nullable types just because one of them might be changed to nullable every couple years just doesn't seem to pass the cost-benefit test for me.

The real issue here isn't the nullables.  The issue is with me and my apparent slowness to respond to these kinds of issues as of late.  I'm hoping this will get better as my schedule gets a little more manageable.  SLA on core-breaking hotfixes should not be measured in weeks, so that one's on me.

**Comment by IsaaacD** [comment]
@sirkris yea that makes sense, I've only been using the project for a couple weeks and didn't put much thought into it in except that having Reddit shift their API responses could be messy. That makes sense to keep the API clean and intuitive, I'm not sure how often Reddit plans to make such changes.

**Comment by sirkris** [comment]
I went ahead and put out a hotfix release.  If you update to version 1.5.2 in NuGet, the library should work again.
