### ISSUE TITLE
Add the ability to get the refresh token from within the app

### ISSUE THREAD

**Issue by Atulin** [sirkris/Reddit.NET#52]
As it stands now, according to the video, the retrieval process of the refresh token is rather cumbersome. I can't imagine any potential users of my app going through the hassle of cloning the repo, building the retrieval tool, getting my app's ID, copying the refresh token, and inputting it somewhere in the finished app.

The library, as it stands, is useful for bot development, but I can't see using it for a desktop/mobile app as viable.

**Comment by sirkris** [comment]
Unfortunately, you would have to talk to whoever maintains the Reddit API
about that, as it's something I have no control over.  Reddit requires a
callback URL for refresh token retrieval, which is the main hurdle that
gets in devs' way.  This application eliminates that problem by opening a
port on localhost, which you can then set as your app's callback URL.

Why don't you just build the refresh tool and include it in your repo?
That would not be a license violation so you're free to do that.
Furthermore, before building, you could easily modify the app to
automatically use your App ID rather than prompting for it.  If you were
going to use this utility in a production setting, that's how I'd recommend
you go about doing it.  Then all they have to do is run the program, click
"Accept" on the Reddit app auth page (nothing I can do about that, either),
then copy the refresh token when it appears.  Or, better still, you could
further modify the app (with barely any effort) to automatically save the
refresh token to whatever configuration store you're using.

I just want to reiterate that you are free to modify, build, and
redistribute this tool in your project as you see fit, so long as you do so
in accordance with the terms of the MIT license (which is really easy to do
as it's a very permissive license).

https://opensource.stackexchange.com/a/6981

https://opensource.stackexchange.com/a/4716

https://github.com/sirkris/Reddit.NET/blob/master/LICENSE


If you run into any trouble adapting the utility for your app, let me know
and I'd be happy to help you through it.

--Kris

**Comment by sirkris** [comment]
In case anybody else finds this, just to eliminate any confusion, the token retrieval app was _not_ designed to be used in a production setting!  While it is certainly stable, as @Atulin pointed out, the workflow is a bit too cumbersome for large-scale use.  It is useful for when you just need to generate a token for testing or whatever, but beyond that I would **strongly** recommend that you modify the source to accommodate your app's specific needs.

An alternative approach to what I suggested in my last comment would be to build the app as-is but have _your_ app run it and pass your App ID as the second argument (first argument is port; defaults to 8080).  Third argument is for the App Secret, if you have one.  The prompts are skipped when you supply the arguments; instead, a browser window should just open and take them to the app auth page.  Once they click accept, you can modify the utility (or just capture its stdout) to grab the refresh token.

Would it be helpful if I created a library version of this utility?  I could then modify the app to just use that and include both of them in the solution.

**Comment by Atulin** [comment]
A pity that Reddit imposes such limitations on the API users, honestly.

Regardless, yes, I believe that having that utility in the form of a simple library would make it a little bit easier than having to dabble with the source code.

The ideal solution would be a built-in function that uses a WebView to display login/authorize prompt,a dn then captures the token via XPath or something of the sorts, but it could be problematic in case of other than default WebViews, like Cefsharp.

**Comment by sirkris** [comment]
Yeah that was my thinking originally, as well, but that would end up making
the library a lot bulkier to support the added dependencies.  That's why I
decided it would be better to make it a separate project.

--Kris

**Comment by hallidev** [comment]
RedditSharp, despite being unmaintained, is able to do this against the current Reddit API:

https://github.com/CrustyJew/RedditSharp

I've been looking forward to someone building a modern / supported wrapper for NetCore, but if it can't do token retrieval, it's a not a viable API wrapper

**Comment by sirkris** [comment]
It will be in the next release.

**Comment by sirkris** [comment]
Here it is:

https://www.nuget.org/packages/Reddit.AuthTokenRetrieverLib

https://github.com/sirkris/Reddit.NET/blob/develop/docs/examples/cs/Authorize%20New%20User.md

**Comment by hallidev** [comment]
Awesome! Looking forward to it. Nice job on this too btw. I just realized
my comment may have come across wrong / unfriendly.

**Comment by sirkris** [comment]
Heh thanks!  Version 1.1.0 should be out within the next week or so.

--Kris

**Comment by KungFuryKeyboard** [comment]
> As it stands now, according to the video, the retrieval process of the refresh token is rather cumbersome. I can't imagine any potential users of my app going through the hassle of cloning the repo, building the retrieval tool, getting my app's ID, copying the refresh token, and inputting it somewhere in the finished app.
> 
> The library, as it stands, is useful for bot development, but I can't see using it for a desktop/mobile app as viable.
....

Just use the use Install-Package AspNet.Security.OAuth.Reddit
  ```
 services.AddAuthentication(options =>
                {
                    options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                })
           
                .AddReddit(options =>
                {
                    options.ClientId = "xxx";
                    options.ClientSecret = "xxx";    
                    options.Scope.Add( "identity" ) ;
                    options.Scope.Add( "read" ) ;
                    options.Scope.Add( "submit" ) ;
                    options.SaveTokens = true;
                });
```

Then if your using Identity make a call on login/register to save ExternalTokens...
you will have the refresh token stored/expiry date etc.. 
you can them implement a regeneration of a token if expired/expiring.

**Comment by sirkris** [comment]
Added in 1.1.0.
