### ISSUE TITLE
Browser doesn’t open local host for token

### ISSUE THREAD

**Issue by FireCubeStudios** [sirkris/Reddit.NET#71]
I was implementing login feature and used the code in authorizenewuser.cs

I used the same code and installed the NuGet package but changed the open browser proccessstartinfo to launch uri async because I’m using uwp. 

When I run the app it launches browser with the Reddit authentication page however when I click accept it says local host can’t be reached.

**Comment by sirkris** [comment]
Woops!  Looks like I forgot to upload the 1.2 package for the auth token retriever lib to NuGet.  They're in the same repo so sometimes I forget I made them two separate packages on NuGet.  My bad.  What you're describing sounds like a bug that was fixed in 1.2.

Anyway, I uploaded the latest version to NuGet now.  Try updating it on your end and let me know if that fixes it for ya.

**Comment by FireCubeStudios** [comment]
it still didn't work. I think its because im using a uwp app which uses .net core and uhttpsharp uses .net framework so it wont work in uwp.
I think for now I will try to use redditsharp to get the token
