### ISSUE TITLE
"Invalid redirect_url parameter" when using AuthTokenRetriever

### ISSUE THREAD

**Issue by derekantrican** [sirkris/Reddit.NET#75]
I'm trying to use AuthTokenRetriever. I cloned the repo, built, and am starting up the AuthTokenRetriever console app. After putting in my app id and secret I get a reddit page with the following message:

![image](https://user-images.githubusercontent.com/1558019/63057337-d938cf80-be9e-11e9-9a52-11f8bc0b7040.png)

What does this mean?

**Comment by pauliyobo** [comment]
Hello. I've actually ran in the same problem.
By inspecting the code it turns out that the AwaitCallback, command hosts the server and wait for the requests at the local url at the port designed by the call which by default is 8080.
However, AuthURL() appends to the the route /Reddit.NET/oauthRedirect which messes up everything.
I've managed to solve my problem partially by doing something like:
AuthURL().replace("/Reddit.NET/oauthRedirect", "");
However my problem is not resolved yet as the reddit authorization page seems to redirect somewhere, but the server doesn't seem to properly process the data. Either that or the server is not properly set up. If you try to go to the URL localhost:8080 you'll see that nothing will happen.

**Comment by colin-haber** [comment]
The `redirect_uri` parameter must _exactly_ match the one you have set in your [app preferences](https://www.reddit.com/prefs/apps). If you set the **redirect uri** preference to _http://localhost:8080/Reddit.NET/oauthRedirect_ it should work.

**Comment by derekantrican** [comment]
@colin-haber Ah, good note. That worked for me. It might be helpful for that to be noted somewhere (maybe in the `Console.WriteLine` lines of the application)

**Comment by pauliyobo** [comment]
I've modified and built the library so that it hosts and the uri points to localhost:8080 but the result is the same. I can't get a proper response. If I press the allow button nothing will happen.

**Comment by derekantrican** [comment]
@pauliyobo per colin's suggestion, I had to modify my redirect url *in settings for the app on reddit* to http://localhost:8080/Reddit.NET/oauthRedirect to get it to work. See screenshot:

![image](https://user-images.githubusercontent.com/1558019/63980051-5ce1e700-ca6f-11e9-952c-2e32035cc28b.png)

**Comment by pauliyobo** [comment]
I've did it already, but it didn't work.
Also, I'm not able to see the screenshot as I'm blind. Would you kindly describe the image you sent?

**Comment by derekantrican** [comment]
@pauliyobo Oh, it was just an image of where to change it on reddit (just a screenshot of what I was describing)

**Comment by sirkris** [comment]
As some have already mentioned, this error is returned by the Reddit API if the "redirect uri" field doesn't *exactly* match what's being passed by the AuthTokenRetriever library.
